name: OCI ARM Capacity Hunter

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-hunter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: curl, json

      - name: Instalar Dependências
        run: composer install --no-dev --prefer-dist --no-progress

      - name: Criar arquivo .env e chaves
        run: |
          echo "${{ secrets.OCI_KEY_CONTENT }}" > private_key.pem
          
          SSH_KEY='${{ secrets.OCI_SSH_PUBLIC_KEY }}'
          if [ -z "$SSH_KEY" ]; then
            ssh-keygen -t rsa -b 2048 -f vm_ssh_key -N ""
            SSH_KEY=$(cat vm_ssh_key.pub)
          fi

          IMAGE_ID="${{ secrets.OCI_IMAGE_ID }}"
          if [ -z "$IMAGE_ID" ]; then
            IMAGE_ID="ocid1.image.oc1.sa-saopaulo-1.aaaaaaaaridfqffskkfnob3bohkol53qhirbl3fwgtkkh4azs4m6hrl7iz7q"
          fi

          cat <<EOF > .env
          OCI_REGION="${{ secrets.OCI_REGION }}"
          OCI_USER_ID="${{ secrets.OCI_USER_OCID }}"
          OCI_TENANCY_ID="${{ secrets.OCI_TENANCY_OCID }}"
          OCI_COMPARTMENT_ID="${{ secrets.OCI_COMPARTMENT_OCID }}"
          OCI_SUBNET_ID="${{ secrets.OCI_SUBNET_OCID }}"
          OCI_IMAGE_ID="$IMAGE_ID"
          OCI_SHAPE="VM.Standard.A1.Flex"
          OCI_SSH_PUBLIC_KEY="$SSH_KEY"
          OCI_KEY_FINGERPRINT="${{ secrets.OCI_FINGERPRINT }}"
          OCI_KEY_FILENAME="private_key.pem"
          OCI_PRIVATE_KEY_FILENAME="private_key.pem"
          OCI_OCPUS="${{ secrets.OCI_MAX_OCPU }}"
          OCI_MEMORY_IN_GBS="${{ secrets.OCI_MAX_MEMORY_IN_GBS }}"
          EOF

      - name: Executar Busca de Capacidade na Oracle
        run: php index.php
