name: OCI ARM Capacity Hunter

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-hunter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: curl, json

      - name: Instalar Dependências
        run: composer install --no-dev --prefer-dist --no-progress

      - name: Executar Busca de Capacidade na Oracle
        env:
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_ID: ${{ secrets.OCI_USER_OCID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_COMPARTMENT_ID: ${{ secrets.OCI_COMPARTMENT_OCID }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_OCID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_KEY_CONTENT: ${{ secrets.OCI_KEY_CONTENT }}
          OCI_OCPUS: ${{ secrets.OCI_MAX_OCPU }}
          OCI_MEMORY_IN_GBS: ${{ secrets.OCI_MAX_MEMORY_IN_GBS }}
        run: php index.php
